- name: Fix it now
  pattern: "[fF][iI][xX][mM][eE]"
  filename:
    - "*.py"

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filename:
    - "*.py"

- name: Leftover print
  pattern: "print\\("
  filename:
    - "*.py"
